[package]
name = "object_store_ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[profile.release]
debug = true

[dependencies]
tokio = { version = "1.32.0", features = ["rt-multi-thread", "macros", "signal", "time"] }
bytes = "1.0"
tracing = "0.1"
tracing-subscriber = "0.3"
futures-util = "0.3"
# object_store = { git = "https://github.com/andrebsguedes/arrow-rs.git", branch = "dns", features = ["azure"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "trust-dns"] }
object_store = { version = "0.8", features = ["azure"] }
thiserror = "1"
anyhow = "1"
once_cell = "1.18"
async-channel = "1.9.0"
crossbeam-queue = "0.3.8"
moka = { version = "0.12.0", features = ["future"] }
url = "2.4"
